"""empty message

Revision ID: 5505219776b1
Revises: fc8bc0e6c094
Create Date: 2020-04-23 18:00:34.694186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5505219776b1'
down_revision = 'fc8bc0e6c094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('ticket_id', sa.INTEGER(), nullable=False),
    sa.Column('departure_time', sa.VARCHAR(length=64), nullable=False),
    sa.Column('arrival_time', sa.VARCHAR(length=64), nullable=False),
    sa.Column('simple', sa.INTEGER(), nullable=False),
    sa.Column('high_class', sa.INTEGER(), nullable=False),
    sa.Column('day', sa.DATETIME(), nullable=False),
    sa.Column('departure_point', sa.VARCHAR(length=64), nullable=False),
    sa.Column('arrival_point', sa.VARCHAR(length=64), nullable=False),
    sa.Column('simple_price', sa.INTEGER(), nullable=False),
    sa.Column('high_price', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    # ### end Alembic commands ###
