"""empty message

Revision ID: a8811123b5ee
Revises: 58f6cb7d72d5
Create Date: 2020-04-23 16:53:25.249821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8811123b5ee'
down_revision = '58f6cb7d72d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('departure_time', sa.Integer(), nullable=False),
    sa.Column('arrival_time', sa.Integer(), nullable=False),
    sa.Column('simple', sa.Integer(), nullable=False),
    sa.Column('high_class', sa.Integer(), nullable=False),
    sa.Column('path_time', sa.Integer(), nullable=False),
    sa.Column('departure_point', sa.String(length=64), nullable=False),
    sa.Column('arrival_point', sa.String(length=64), nullable=False),
    sa.Column('simple_price', sa.Integer(), nullable=False),
    sa.Column('high_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    # ### end Alembic commands ###
