"""empty message

Revision ID: ddbbbb75f2bc
Revises: a8811123b5ee
Create Date: 2020-04-23 17:41:13.070884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddbbbb75f2bc'
down_revision = 'a8811123b5ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('ticket_id', sa.INTEGER(), nullable=False),
    sa.Column('departure_time', sa.INTEGER(), nullable=False),
    sa.Column('arrival_time', sa.INTEGER(), nullable=False),
    sa.Column('simple', sa.INTEGER(), nullable=False),
    sa.Column('high_class', sa.INTEGER(), nullable=False),
    sa.Column('path_time', sa.INTEGER(), nullable=False),
    sa.Column('departure_point', sa.VARCHAR(length=64), nullable=False),
    sa.Column('arrival_point', sa.VARCHAR(length=64), nullable=False),
    sa.Column('simple_price', sa.INTEGER(), nullable=False),
    sa.Column('high_price', sa.INTEGER(), nullable=False),
    sa.Column('day', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    # ### end Alembic commands ###
