"""empty message

Revision ID: fc8bc0e6c094
Revises: ddbbbb75f2bc
Create Date: 2020-04-23 17:43:01.654062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc8bc0e6c094'
down_revision = 'ddbbbb75f2bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('departure_time', sa.String(length=64), nullable=False),
    sa.Column('arrival_time', sa.String(length=64), nullable=False),
    sa.Column('simple', sa.Integer(), nullable=False),
    sa.Column('high_class', sa.Integer(), nullable=False),
    sa.Column('day', sa.DateTime(), nullable=False),
    sa.Column('departure_point', sa.String(length=64), nullable=False),
    sa.Column('arrival_point', sa.String(length=64), nullable=False),
    sa.Column('simple_price', sa.Integer(), nullable=False),
    sa.Column('high_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    # ### end Alembic commands ###
